name: floodwise-ph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    # Core dependencies
    - streamlit==1.28.1
    - pandas==2.1.3
    - numpy==1.24.3
    - python-dotenv==1.0.0
    
    # OpenAI
    - openai==1.3.5
    
    # Fuzzy matching
    - fuzzywuzzy==0.18.0
    - python-Levenshtein==0.12.2
    
    # HTTP client
    - httpx==0.25.0
