[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
baseUrlPath = "/"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

# Mobile optimization settings
[ui]
hideTopBar = false

# Disable file watcher for better performance in cloud
[server]
fileWatcherType = "none"

# Disable websocket compression for better performance
[server.enableWebsocketCompression]
false = true
hideSidebarNav = false
