[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
baseUrlPath = "/"
fileWatcherType = "none"
enableStaticServing = true
enableWebsocketCompression = false
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = false

# Enable built-in health checks
[server.health]
enabled = true
path = "/healthz"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[ui]
hideTopBar = false
hideSidebarNav = false

# Disable websocket compression for better performance
[server.enableWebsocketCompression]
enabled = false
